### ISSUE TITLE
Doesn't start after installation (Gtk-Message: Failed to load module "canberra-gtk-module")

### ISSUE THREAD

**Issue by damian101** [egara/buttermanager#20]
I just installed ButterManager with the snap package on openSUSE Tumbleweed, but when I try to open it, it doesn't start.
Here is the terminal output:
```
damian101@localhost:~> buttermanager
Gtk-Message: Failed to load module "canberra-gtk-module"
_IceTransSocketUNIXConnect: Cannot connect to non-local host localhost
_IceTransSocketUNIXConnect: Cannot connect to non-local host localhost
Qt: Session management error: Could not open network socket

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32

(python3:30946): Gtk-WARNING **: /usr/lib/gtk-2.0/2.10.0/engines/libpixmap.so: wrong ELF class: ELFCLASS32
Traceback (most recent call last):
  File "/snap/buttermanager/x2/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/snap/buttermanager/x2/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/snap/buttermanager/x2/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/snap/buttermanager/x2/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/snap/buttermanager/x2/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/snap/buttermanager/x2/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/snap/buttermanager/x2/usr/lib/python3.5/http/client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "/snap/buttermanager/x2/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/snap/buttermanager/x2/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/snap/buttermanager/x2/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/snap/buttermanager/x2/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/buttermanager/x2/buttermanager/util/utils.py", line 200, in check_version
    response = urllib.request.urlopen(self.__version_url)
  File "/snap/buttermanager/x2/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/snap/buttermanager/x2/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/snap/buttermanager/x2/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/snap/buttermanager/x2/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/snap/buttermanager/x2/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/snap/buttermanager/x2/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "buttermanager.py", line 865, in <module>
    password_window = PasswordWindow(None)
  File "buttermanager.py", line 69, in __init__
    self.init_ui()
  File "buttermanager.py", line 108, in init_ui
    self.__version_checker.check_version()
  File "/snap/buttermanager/x2/buttermanager/util/utils.py", line 206, in check_version
    self.__logger.error("Error checking new versions of ButterManager. Reason: " + exception.reason)
TypeError: Can't convert 'ssl.SSLError' object to str implicitly
damian101@localhost:~>
```

**Comment by damian101** [comment]
I get a very similar output on Arch Linux in VirtualBox:
```
[damian101@VBox-RebornOS Downloads]$ buttermanager
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
Traceback (most recent call last):
  File "/snap/buttermanager/x1/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/snap/buttermanager/x1/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/snap/buttermanager/x1/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/snap/buttermanager/x1/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/snap/buttermanager/x1/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/snap/buttermanager/x1/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/snap/buttermanager/x1/usr/lib/python3.5/http/client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "/snap/buttermanager/x1/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/snap/buttermanager/x1/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/snap/buttermanager/x1/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/snap/buttermanager/x1/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/snapd/snap/buttermanager/x1/buttermanager/util/utils.py", line 200, in check_version
    response = urllib.request.urlopen(self.__version_url)
  File "/snap/buttermanager/x1/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/snap/buttermanager/x1/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/snap/buttermanager/x1/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/snap/buttermanager/x1/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/snap/buttermanager/x1/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/snap/buttermanager/x1/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "buttermanager.py", line 865, in <module>
    password_window = PasswordWindow(None)
  File "buttermanager.py", line 69, in __init__
    self.init_ui()
  File "buttermanager.py", line 108, in init_ui
    self.__version_checker.check_version()
  File "/var/lib/snapd/snap/buttermanager/x1/buttermanager/util/utils.py", line 206, in check_version
    self.__logger.error("Error checking new versions of ButterManager. Reason: " + exception.reason)
TypeError: Can't convert 'ssl.SSLError' object to str implicitly
[damian101@VBox-RebornOS Downloads]$
```

**Comment by damian101** [comment]
On my openSUSE Tumbleweed installation in VirtualBox it also doesn't start, but the terminal output is different:
```
test@linux-ew6n:~> buttermanager
/snap/buttermanager/x2/bin/desktop-launch: line 385: /snap/buttermanager/x2/usr/lib/x86_64-linux-gnu/glib-2.0/gio-querymodules: No such file or directory
/snap/buttermanager/x2/bin/desktop-launch: line 413: /snap/buttermanager/x2/usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas: No such file or directory
/snap/buttermanager/x2/bin/desktop-launch: line 442: /snap/buttermanager/x2/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders: No such file or directory
/snap/buttermanager/x2/bin/desktop-launch: line 554: /snap/buttermanager/x2/usr/bin/python3: No such file or directory
test@linux-ew6n:~>
```

**Comment by egara** [comment]
Hi @damian101 and thank you very much for your report.

I'll take a look, because the snap package is a little bit outdated (current version is 1.9). I don't know if it is worth creating a package with the new version or maybe I create a install script because I have found that ButterManager works fine creating a virtual environment with Python.

So I'm going to work on it and I'll keep you inform :)

By the way, in Arch you can install the application via AUR without any problem https://aur.archlinux.org/packages/buttermanager/

**Comment by egara** [comment]
Hi @damian101 again!

I've been working on a installation script. Please, did you have time to test it on those environments and tell me if it works?

You have to clone this repository and checkout branch devel: 

`git checkout devel`

Install possible missing dependencies like **python3-setuptools** and **python3-venv** packages (maybe the name of these packages are different in those distributions).

Then, enter /install directory and execute **install.sh**

This script should install ButterManager in a virtual environment and create a desktop launcher to execute it.

I will abandon the idea of creating a snap package because this kind of tools are difficult to isolate using this technology.

**Comment by damian101** [comment]
@egara Those steps worked fine on Arch, Ubuntu and openSUSE, thanks!
