### ISSUE TITLE
Snapshot error in logs

### ISSUE THREAD

**Issue by KimHono** [egara/buttermanager#42]
Hi, I notice a snapshot error in a log.
How to reproduce:

- I clicked on "update with snapshot button". Everything worked fine.
- Then I opened the resulting log file. There, I notice the following error:

```
Checking for system updates. 
-------- 

-------- 
Starting system upgrading process. Please wait... 

-------- 
Creating snapshots and updating GRUB entries if it is necessary... 
-------- 
Create a snapshot of '/mnt/defvol/@/' in '/mnt/defvol/snapshots/root-20211024-0' 

-------- 
Error creating the snapshot /mnt/defvol/@/ 
Error: 'NoneType' object has no attribute 'decode' 
-------- 
Upgrading the system. Please wait... 
:: Synchronising package databases... 
core downloading... 
extra downloading... 
community downloading... 
multilib downloading... 
endeavouros downloading... 
:: Starting full system upgrade... 
resolving dependencies... 
looking for conflicting packages...
``` 

- Finally, I tried to do several snapshots in command line, outside ButterManager. No error message appeared.

Maybe ButterManager is involved in this case ?

Best regards

**Comment by KimHono** [comment]
Hi @egara, it's cool we both use EndeavourOS !
Btw, I forgot to write my ButterManager version, which is 2.4.2.

As you asked, here is my configuration file:
_aur_repository: 0
check_at_startup: 0
grub_btrfs: 1
path_to_consolidate_root_snapshot: '@'
save_log: 1
snap_packages: 0
subvolumes_dest: /mnt/defvol/snapshots/
subvolumes_orig: /mnt/defvol/@/
subvolumes_prefix: root
subvolumes_snapshots_to_keep: '3'_

And here is the exception I received while using the "Take snapshot" button on the main window:
_Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/buttermanager/buttermanager/window/windows.py", line 418, in take_snapshot
    settings.subvolumes[subvolume].create_snapshot()
  File "/usr/lib/python3.9/site-packages/buttermanager/buttermanager/filesystem/snapshot.py", line 157, in create_snapshot
    commandline_output = commandline_output.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'
Aborted (core dumped)_

Thanks for this very useful application !

**Comment by egara** [comment]
Hi @KimHono and thanks for the information and your words! I'm very glad that you find ButterManager useful for you :)

Your configuration file seems to be fine and about the stack trace... it is something weird. Is your locale UTF-8 or are you using another one? (you can check it our opening a terminal and typing locale)

Again, thank you very much :D

**Comment by KimHono** [comment]
Hi @egara, nothing special with my locale, it's `LANG=en_GB.UTF-8`.
Buttermanager is crashing when using this function on the main window, however the snapshots are successful.

I hope it will help you debugging...

**Comment by egara** [comment]
Thanks for the info @KimHono 

I'm a little bit lost but I'll investigate on it and tell you something :)

**Comment by KimHono** [comment]
Thanks !
