### ISSUE TITLE
built/installed, errors out from cli, nothing from gui

### ISSUE THREAD

**Issue by iconoclasthero** [egara/buttermanager#54]
```
$ /usr/local/bin/buttermanager 
Traceback (most recent call last):
  File "/usr/local/bin/buttermanager", line 33, in <module>
    sys.exit(load_entry_point('buttermanager==2.5.0', 'console_scripts', 'buttermanager')())
  File "/usr/local/bin/buttermanager", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/buttermanager-2.5.0-py3.10.egg/buttermanager/bm_main.py", line 1, in <module>
    from .buttermanager.buttermanager import PasswordWindow
  File "/usr/local/lib/python3.10/dist-packages/buttermanager-2.5.0-py3.10.egg/buttermanager/buttermanager/buttermanager.py", line 20, in <module>
    from .filesystem import filesystem, snapshot
  File "/usr/local/lib/python3.10/dist-packages/buttermanager-2.5.0-py3.10.egg/buttermanager/buttermanager/filesystem/filesystem.py", line 24, in <module>
    from ..window import windows
  File "/usr/local/lib/python3.10/dist-packages/buttermanager-2.5.0-py3.10.egg/buttermanager/buttermanager/window/windows.py", line 23, in <module>
    from ..filesystem import snapshot
  File "/usr/local/lib/python3.10/dist-packages/buttermanager-2.5.0-py3.10.egg/buttermanager/buttermanager/filesystem/snapshot.py", line 24, in <module>
    from ..util import settings, utils
  File "/usr/local/lib/python3.10/dist-packages/buttermanager-2.5.0-py3.10.egg/buttermanager/buttermanager/util/settings.py", line 22, in <module>
    from . import utils
  File "/usr/local/lib/python3.10/dist-packages/buttermanager-2.5.0-py3.10.egg/buttermanager/buttermanager/util/utils.py", line 26, in <module>
    from PyQt5.QtWidgets import QFileDialog
ImportError: /usr/local/lib/python3.10/dist-packages/PyQt5-5.15.10-py3.10-linux-x86_64.egg/PyQt5/QtWidgets.abi3.so: undefined symbol: _ZdlPvm, version Qt_5
```

**Comment by egara** [comment]
Hi @iconoclasthero 

What distro are you using to install ButterManager? Are you on Arch or derivatives?
