### ISSUE TITLE
QThread error

### ISSUE THREAD

**Issue by mriza** [egara/buttermanager#58]
I installed Buttermanager today and got error like this:

QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/usr/bin/buttermanager", line 33, in <module>
    sys.exit(load_entry_point('buttermanager==2.4.2', 'console_scripts', 'buttermanager')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/buttermanager/bm_main.py", line 17, in main
    PasswordWindow(None)
  File "/usr/lib/python3.12/site-packages/buttermanager/buttermanager/buttermanager.py", line 60, in __init__
    self.__buttermanager_configurator.configure()
  File "/usr/lib/python3.12/site-packages/buttermanager/buttermanager/util/utils.py", line 140, in configure
    self.migrate_properties()
  File "/usr/lib/python3.12/site-packages/buttermanager/buttermanager/util/utils.py", line 184, in migrate_properties
    snapshots_to_keep = int(settings.properties_manager.get_property('snapshots_to_keep'))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

**Comment by egara** [comment]
Hi @mriza and thanks for your feedback.

What distro are you using and how have you installed ButterManager?

**Comment by mriza** [comment]
I'm using Fedora 40 and installed Buttermanager using dnf
sudo dnf install buttermanager

**Comment by egara** [comment]
Hi @mriza again.

This is a known issue with Fedora. The package hasn't been updated for a while so it doesn't work anymore. I don't know if the package is going to be updated, because I don't manage it.

But if you want to use ButterManager, you can install it via a installation script created in this repo. I attach an old and closed issue with all the information needed [here](https://github.com/egara/buttermanager/issues/55).

I hope it works!
